### ISSUE TITLE
Setup Kanban Board.

### ISSUE THREAD

**Issue by mailsg** [mailsg/React-Capstone-Space-Travellers-Hub#28]
Hi,

Project Repository Link : https://github.com/mailsg/React-Capstone-Space-Travellers-Hub

Student A : @techmoves 
Student B : @mailsg 

Thanks.

**Comment by Davidosky007** [comment]
Hi @mailsg @techmoves 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a broken link to the Kanban board, Kindly fix it [this is the right link you should provide ](https://github.com/mailsg/React-Capstone-Space-Travellers-Hub/projects/1)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
